- name: Ensure filebeat apt key is present
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  tags: [ apt ]

- name: Install apt-transport-https  
  apt:
    name: apt-transport-https
    state: present
  become: yes
  tags: [ installation ]

- name: Ensure filebeat apt repository is present
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
  tags: [ apt ]

- name: Install filebeat
  apt: 
    name: filebeat
    state: present
    update_cache: yes
  tags: [ installation ]

- name: Replace filebeat.yml file
  template: 
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    mode: '0644'

- name: Restart filebeat
  service:
    name: filebeat
    state: restarted
    enabled: yes
  become: yes