- name: Update repositories cache and install "nginx, prometheus" package
  apt:
    name: 
      - nginx
      - prometheus
    state: latest
    update_cache: yes

- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Create nginx config from template
  template: 
    backup: yes
    src: nginx.conf.j2
    dest: "{{ nginx_config_file }}"

- name: Restart nginx
  service:
    name: nginx
    state: restarted


- name: prometheus config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200