- hosts: tank_nodes,cassandra_nodes
  roles:

- hosts: proxy_nodes
  become: true
  tasks:
  - include_role:  
      name: nginx
    when: ( cloud_provider != "aws" )

- hosts: proxy_nodes
  become: true
  roles:
  - metrics
  - exhauster
  - elk-stack
  