- import_playbook: docker.yml
- import_playbook: node_exporter.yml
- import_playbook: proxy_nodes.yml
- import_playbook: cassandra_nodes.yml
- import_playbook: tank_backend.yml
- import_playbook: tank_frontend.yml
