- name: Stop and remove MongoDB
  docker_container:
    name: mongo
    state: absent

- name: Stop and remove Tank Exhauster
  docker_container:
    name: exhauster
    state: absent

- name: Create docker container mongodb
  docker_container:
    name: mongo 
    image: mongo:latest
    restart: yes
    restart_policy: always
    pull: yes 

- name: Create docker container tank exhauster
  docker_container:
    name: exhauster 
    image: geocode.igd.fraunhofer.de:4567/marauder/exhauster:latest
    restart: yes
    restart_policy: always
    pull: yes
    links:
    - "mongo:mongo"
    ports:
    - "8082:8080"
    env:
      EXHAUSTER_MONGO_HOST: "mongo"
      