- name: Stop and remove Tank Navigator
  docker_container:
    name: navigator
    state: absent

- name: Create a directory if it does not exist
  file:
    path: "{{ navigator_config_file | dirname }}"
    state: directory
    recurse: true
    mode: '0755'

- name: Create Navigator config from template
  template: 
    backup: yes
    src: navigator.json.j2
    dest: "{{ navigator_config_file }}"

- name: Copy Navigator nginx config
  copy:
    src: nginx.conf
    dest: /opt/navigator/nginx.conf
    mode: '644'

- name: Create docker container tank navigator
  docker_container:
    name: navigator 
    image: ap3rture/navigator:latest
    restart: yes
    restart_policy: always
    pull: yes
    ports:
    - "8081:80"
    volumes:
    - "{{ navigator_config_file }}:/usr/share/nginx/html/config.json"
    - "/opt/navigator/nginx.conf:/etc/nginx/nginx.conf"
