- name: Add the public key
  apt_key: 
    keyserver: pool.sks-keyservers.net
    id: "{{ public_key }}"

- name: Add the Apache repository of Cassandra
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 36x main
    filename: cassandra.sources.list

- name: Update repositories cache and install "cassandra" package
  apt:
    name: cassandra=3.11.3
    update_cache: yes

- name: Stop Cassandra
  service:
    name: cassandra
    state: stopped

- name: Install "python-lxml" package as requirement for maven_artifact module
  apt:
    name: python3-lxml

- name: Download jts-core maven_artifact
  get_url:
   url: http://central.maven.org/maven2/com/stratio/cassandra/cassandra-lucene-index-plugin/3.11.3.0/cassandra-lucene-index-plugin-3.11.3.0.jar
   dest: /usr/share/cassandra/lib/
   mode: 644

- name: Download cassandra-lucene-index-plugin maven_artifact
  get_url:
   url: http://central.maven.org/maven2/com/vividsolutions/jts-core/1.14.0/jts-core-1.14.0.jar
   dest: /usr/share/cassandra/lib/
   mode: 644

- name: Create Cassandra config from template
  template: 
    backup: yes
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_file }}"

- name: Remove data directory
  file:
    path: /var/lib/cassandra/data/system/
    state: absent

- name: Restart Cassandra
  service:
    name: cassandra
    state: restarted
