- name: Add the public key
  apt_key: 
    keyserver: pool.sks-keyservers.net
    id: "{{ public_key }}"

- name: Add the Apache repository of Cassandra
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 311x main
    filename: cassandra.sources.list

- name: Update repositories cache and install "cassandra" package
  apt:
    name: cassandra=3.11.4
    allow_unauthenticated: yes
    update_cache: yes
    
- name: Stop Cassandra
  service:
    name: cassandra
    state: stopped

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ ansible_hostname }}'
    state: present

- name: Download jts-core maven_artifact
  get_url:
   url: http://central.maven.org/maven2/com/stratio/cassandra/cassandra-lucene-index-plugin/3.11.3.0/cassandra-lucene-index-plugin-3.11.3.0.jar
   dest: /usr/share/cassandra/lib/
   mode: 644

- name: Download cassandra-lucene-index-plugin maven_artifact
  get_url:
   url: http://central.maven.org/maven2/com/vividsolutions/jts-core/1.14.0/jts-core-1.14.0.jar
   dest: /usr/share/cassandra/lib/
   mode: 644

- name: Create Cassandra config from template
  template: 
    backup: yes
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_file }}"

- name: Remove Cassandra JAVA_OPTS JMX line
  lineinfile:
    path: /etc/cassandra/cassandra-env.sh
    state: absent
    regexp: '^(.*)jmx_prometheus(.*)$'

- name: Add Cassandra JAVA_OPTS JMX line
  lineinfile:
    path: /etc/cassandra/cassandra-env.sh
    line: JVM_OPTS="$JVM_OPTS -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent-0.12.0.jar=7070:/opt/jmx_prometheus/cassandra.yml"
    create: yes

- name: Remove cassandra directory
  file:
    path: "{{ cassandra_data_dir }}"
    state: absent
  when: ( pruneData|default(False)|bool )

- name: Unmount DB Volume
  mount:
    path: /opt/data
    state: unmounted
  when: ( (pruneData and use_db_vol) |default(False)|bool )

- name: Create a ext4 filesystem on /dev/xvdf
  filesystem:
    fstype: ext4
    force: true
    dev: "{{ db_vol }}"
  when: ( (pruneData and use_db_vol) |default(False)|bool )

- name: Mount up DB Volume
  mount:
    path: /opt/data
    src: "{{ db_vol }}"
    fstype: ext4
    state: mounted
    opts: defaults,nofail
  when: ( (pruneData and use_db_vol) |default(False)|bool )

- name: Create cassandra directory
  file:
    path: "{{ cassandra_data_dir }}"
    owner: cassandra
    state: directory

- name: Create commitlog directory
  file:
    path: "{{ cassandra_commitlog_dir }}"
    owner: cassandra
    state: directory

- name: Create hint directory
  file:
    path: "{{ cassandra_hint_dir }}"
    owner: cassandra
    state: directory

- name: Create JMX exporter directory
  file:
    path: /opt/jmx_prometheus
    owner: cassandra
    state: directory

- name: Copy jmx config
  copy:
    src: cassandra_jmx.yml
    dest: /opt/jmx_prometheus/cassandra.yml
    owner: cassandra
    group: cassandra
    mode: '644'

- name: Download jmx exporter maven_artifact
  get_url:
   url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar
   dest: /opt/jmx_prometheus/
   mode: 644
 
- name: Restart Cassandra
  service:
    name: cassandra
    state: restarted
