- name: Add the public key
  apt_key: 
    keyserver: pool.sks-keyservers.net
    id: "{{ public_key }}"

- name: Add the Apache repository of Cassandra
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 311x main
    filename: cassandra.sources.list

- name: Update repositories cache and install "cassandra" package
  apt:
    name: cassandra=3.11.4
    allow_unauthenticated: yes
    update_cache: yes

- name: Install Prometheus Node Exporter
  apt:
    name: prometheus-node-exporter
    allow_unauthenticated: yes
    update_cache: yes

- name: Stop Cassandra
  service:
    name: cassandra
    state: stopped

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ ansible_hostname }}'
    state: present

- name: Download jts-core maven_artifact
  get_url:
   url: http://central.maven.org/maven2/com/stratio/cassandra/cassandra-lucene-index-plugin/3.11.3.0/cassandra-lucene-index-plugin-3.11.3.0.jar
   dest: /usr/share/cassandra/lib/
   mode: 644

- name: Download cassandra-lucene-index-plugin maven_artifact
  get_url:
   url: http://central.maven.org/maven2/com/vividsolutions/jts-core/1.14.0/jts-core-1.14.0.jar
   dest: /usr/share/cassandra/lib/
   mode: 644

- name: Create Cassandra config from template
  template: 
    backup: yes
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_file }}"

- name: Remove cassandra directory
  file:
    path: /var/lib/cassandra/
    state: absent

- name: Create cassandra directory
  file:
    path: /var/lib/cassandra/
    owner: cassandra
    state: directory

- name: Restart Cassandra
  service:
    name: cassandra
    state: restarted
