- name: Add the public key
  apt_key: 
    keyserver: pool.sks-keyservers.net
    id: "{{ public_key }}"

- name: Add the Apache repository of Cassandra
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 36x main
    filename: cassandra.sources.list

- name: Update repositories cache and install "cassandra" package
  apt:
    name: cassandra
    update_cache: yes

- name: Stop Cassandra
  service:
    name: cassandra
    state: stopped

- name: Install "python-lxml" package as requirement for maven_artifact module
  apt:
    name: python-lxml

- maven_artifact:
   group_id: com.vividsolutions
   artifact_id: jts-core
   version: 1.14.0
   dest: /usr/share/cassandra/lib/jts-core-1.14.0.jar

- maven_artifact:
   group_id: com.stratio.cassandra
   artifact_id: cassandra-lucene-index-plugin
   version: 3.11.3.0
   dest: /usr/share/cassandra/lib/cassandra-lucene-index-plugin-3.11.3.0.jar

- name: Create Cassandra config from template
  template: 
    backup: yes
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_file }}"

- name: Remove data directory
  file:
    path: /var/lib/cassandra/data/system/
    state: absent

- name: Restart Cassandra
  service:
    name: cassandra
    state: restarted