- name: Stop and remove Tank
  docker_container:
    name: tank
    state: absent

- name: Prune Docker
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes

- name: Create docker container tank
  docker_container:
    name: tank 
    image: geocode.igd.fraunhofer.de:4567/marauder/tank:latest
    restart: yes
    restart_policy: always
    pull: yes
    ports:
    - "8888:8888"
    env:
      JAVA_OPTS: "-Xms1g -Xmx1g"
      TANK_DB_HOSTS: "{{ cassandra_nodes }}"
      TANK_DB_STRATEGY: NetworkTopologyStrategy
      TANK_DB_REPL: "3"
      TANK_DB_INDEX: "us_idx"
      TANK_MAIN_ATTR: ""
      TANK_MAIN_ATTR_DEFAULT: ""
      TANK_ADD_TIMESTAMP: "true"
      TANK_PARTITION_KEYS: "hash"
      TANK_PRIMARY_KEYS: "timestamp"
      TANK_ATTR_FIELDS: "timestamp timestamp, postcode int, city text, road text, area double, county text, id int, lat double, lon double"
      TANK_DB_TABLE: "buildings"
