- name: Stop and remove Tank
  docker_container:
    name: tank
    state: absent

- name: Stop and remove Tank Navigator
  docker_container:
    name: navigator
    state: absent

- name: Prune Docker
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes

- name: Create docker container tank
  docker_container:
    name: tank 
    image: geocode.igd.fraunhofer.de:4567/marauder/tank:latest
    restart: yes
    restart_policy: always
    pull: yes
    ports:
    - "8888:8888"
    volumes:
    - /var/log/tank:/app/logs
    env:
      JAVA_OPTS: "-Xms2g -Xmx2g"
      TANK_DB_HOSTS: "{%- for host in groups['cassandra_nodes'] -%}
      {{ hostvars[host]['ansible_default_ipv4']['address'] }}{% if not loop.last %},{% endif %}
      {%- endfor -%}"
      TANK_DB_STRATEGY: NetworkTopologyStrategy
      TANK_DB_REPL: "3"
      TANK_DB_INDEX: "us_idx"
      TANK_MAIN_ATTR: ""
      TANK_MAIN_ATTR_DEFAULT: ""
      TANK_ADD_TIMESTAMP: "true"
      TANK_PARTITION_KEYS: "hash"
      TANK_PRIMARY_KEYS: "timestamp"
      TANK_ATTR_FIELDS: "timestamp timestamp, postcode text, city text, road text, area double, county text, id int, lat double, lon double"
      TANK_TILE_ATTRIBUTES: "postcode, city, area, road, lon, lat, county"
      TANK_DB_TABLE: "buildings"
      TANK_EXHAUSTER_ENABLED: "true"
      TANK_EXHAUSTER_HOST: "{{ hostvars[groups['proxy_nodes'][0]]['ansible_default_ipv4']['address'] }}"
      TANK_EXHAUSTER_PORT: "8082"

- name: Create a directory if it does not exist
  file:
    path: "{{ navigator_config_file | dirname }}"
    state: directory
    recurse: true
    mode: '0755'

- name: Create Navigator config from template
  template: 
    backup: yes
    src: navigator.json.j2
    dest: "{{ navigator_config_file }}"

- name: Create docker container tank navigator
  docker_container:
    name: navigator 
    image: geocode.igd.fraunhofer.de:4567/marauder/navigator:latest
    restart: yes
    restart_policy: always
    pull: yes
    ports:
    - "8081:80"
    volumes:
    - "{{ navigator_config_file }}:/usr/share/nginx/html/config.json"
