- name: Update repositories cache and install "prometheus" package
  apt:
    name: 
      - prometheus
    state: latest
    update_cache: yes

- name: prometheus config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.yml

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted

- name: Wait for Prometheus running
  wait_for:
    port: 9090
    delay: 5

- name: ensure grafana apt key is present
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  tags: [ apt ]

- name: ensure grafana apt repository is present
  apt_repository:
    repo="deb https://packages.grafana.com/oss/deb stable main"
    update_cache=yes
    state=present
  become: yes
  tags: [ apt ]

- name: ensure grafana is installed
  apt:
    name=grafana
    state=present
  become: yes
  tags: installation

- name: Set root_url for grafana
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^(.*)root_url(.*)$'
    line: "root_url = http://{{ proxy_node_public_ip }}/grafana"
    create: yes

- name: ensure grafana is running and enabled to start on boot
  service:
    name=grafana-server
    state=started
    enabled=yes
  become: yes

- name: Restart grafana
  service:
    name: grafana-server
    state: restarted

- name: Wait for grafana running
  wait_for:
    port: 3000
    delay: 10

- name: Create prometheus datasource
  grafana_datasource:
    name: "prometheus"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    is_default: yes
    ds_type: "prometheus"
    url: "http://localhost:9090"

- name: Import grafana full dashboard through API
  uri:
    url: "http://localhost:3000/api/dashboards/db"
    user: "admin"
    password: "admin"
    force_basic_auth: true
    method: POST
    body_format: json
    body: >
      {
        "dashboard": {{ lookup("file", "host-metrics_rev4.json") }},
        "overwrite": true,
        "message": "Updated by ansible"
      }

- name: Import grafana simple dashboard through API
  uri:
    url: "http://localhost:3000/api/dashboards/db"
    user: "admin"
    password: "admin"
    force_basic_auth: true
    method: POST
    body_format: json
    body: >
      {
        "dashboard": {{ lookup("file", "tank_metrics.json") }},
        "overwrite": true,
        "message": "Updated by ansible"
      }

